name: reader
description: "Reader module"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Module dùng chung
  shared_dependencies:
    path: ../shared_dependencies
  
  # Module liên quan (để lưu progress)
  library_manga:
    path: ../library
  catalog:
    path: ../catalog
dev_dependencies:
  flutter_test:
    sdk: flutter