name: manga_reader_app
description: Manga reader using MangaDex API (Flutter + MangaDex API + modular DDD)
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  dio: ^5.5.0
  cached_network_image: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.7.0
  go_router: ^14.2.0
  meta: ^1.15.0

  # modules nội bộ
  discovery:
    path: modules/discovery
  catalog:
    path: modules/catalog
  reader:
    path: modules/reader
  library_manga:
    path: modules/library
  home:
    path: modules/home

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true