name: manga_reader_app
description: Manga reader using MangaDex API
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Modules
  shared_dependencies:
    path: modules/shared_dependencies
  core:
    path: modules/core

  # Feature Modules
  auth:
    path: modules/auth
  home:
    path: modules/home
  discovery:
    path: modules/discovery
  catalog:
    path: modules/catalog
  library_manga:
    path: modules/library
  reader:
    path: modules/reader

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true