name: home
description: "Home module"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  shared_dependencies:
    path: ../shared_dependencies
  
  # Phụ thuộc vào các module cung cấp dữ liệu
  discovery:
    path: ../discovery
  library_manga:
    path: ../library

dev_dependencies:
  flutter_test:
    sdk: flutter