name: home
description: "Home module: continue reading + trending feed"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  meta: ^1.15.0
  flutter_bloc: ^8.1.4
  get_it: ^7.7.0

  # chú ý: tên key ở đây PHẢI đúng bằng `name:` của module kia
  library_manga:
    path: ../library

  discovery:
    path: ../discovery
