name: auth
description: Authentication module
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Chỉ depend vào shared và core, không liệt kê lẻ tẻ
  shared_dependencies:
    path: ../shared_dependencies
  core:
    path: ../core


dev_dependencies:
  flutter_test:
    sdk: flutter