name: auth
description: Authentication module using Firebase
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  get_it: ^7.7.0
  
  # Firebase
  firebase_auth: ^4.17.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter