name: library_manga
description: Library module
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_dependencies:
    path: ../shared_dependencies
  core:
    path: ../core
  auth:
    path: ../auth