name: library_manga
description: "Library module: favorites, reading history, continue reading"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  meta: ^1.15.0
  flutter_bloc: ^8.1.4
  get_it: ^7.7.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

  auth:
    path: ../auth