name: catalog
description: "Catalog module: search manga, manga detail, chapters list"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  library_manga:
    path: ../library
  shared_dependencies:
    path: ../shared_dependencies
  auth:
    path: ../auth
