name: catalog
description: "Catalog module: search manga, manga detail, chapters list"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  library_manga:
    path: ../library

  dio: ^5.5.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  meta: ^1.15.0
  cached_network_image: ^3.3.1
  async: ^2.11.0
