name: discovery
description: "Discovery module: trending manga, latest updates feeds for home screen"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # Network
  dio: ^5.5.0

  # Service locator DI
  get_it: ^7.7.0

  # Cached image for UI widget
  cached_network_image: ^3.3.1

  # meta for annotations like @immutable
  meta: ^1.15.0
